Show erroying path when getting the wallet
infinity-swap/ic-test-utils pull request #5
Opened 2022-06-22 11:53 UTC by awkure

Revert the change that was merged previously

2022-09-12 09:33 UTC, hagsteel approved these changes

2022-09-19 10:24 UTC, F3kilo requested changes
I tried to build the package, but can't due to a lot of errors like:
```
#[derive(Debug, CandidType, Deserialize)]
    |                         ^^^^^^^^^^ the trait `candid::CandidType` is not implemented for `ic_agent::export::Principal`
```
Looks like dependencies issue.

2022-09-19 10:24 UTC, F3kilo commented on src/canister/wallet.rs
> +    let wallet_id_path = PathBuf::from(wallet_id_path.into().unwrap_or(WALLET_IDS_PATH));
```suggestion
    let path_str = wallet_id_path.into().unwrap_or(WALLET_IDS_PATH);
    let wallet_id_path = PathBuf::from(path_str);
```
Looks more readable for me.

2022-09-19 10:24 UTC, F3kilo commented on src/canister/wallet.rs
> +        e @ Err(_) => e?,
```suggestion
        e => e?,
```

Not necessary to use `@`.

2022-09-19 11:38 UTC, rumatoest approved these changes

2022-09-20 12:38 UTC, closed without merging